### ISSUE TITLE
no caustics in rendering image

### ISSUE THREAD

**Issue by wenxiwu777** [OscarShen/OpenRayTracing#1]
hi, i use the caustic-glass.xml in the scenes directory to render with your ray tracer, but there is no caustics in final image, it's big different in comparison to the image you posted here, so i'm wandering if the version of code in the repo is the latest one.

**Comment by OscarShen** [comment]
你好，这个项目是练习项目，本地已经没有备份了。

但是，代码是没有修改的。如果确实需要的话，可以修改一下 spot light 和 sppm integrator 的参数测试一下。
